# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

target 'TrivverDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for Trivver
  
  pod 'TrivverSDK'


end

post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
        if config.name == 'Debug'
            config.build_settings['OTHER_SWIFT_FLAGS'] ||= ['$(inherited)', '-D DEBUG']
            elsif config.name == 'Release'
            config.build_settings['OTHER_SWIFT_FLAGS'] ||= ['$(inherited)', '-D RELEASE']
        end
        config.build_settings['SWIFT_VERSION'] = '3.0'
    end
end
