#import <Foundation/Foundation.h>
#import "SMBaseObject.h"

/**
* Trivver API Development
* API for Trivver project
*
* OpenAPI spec version: 0.0.107
* Contact: trivver@saritasa.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/



@protocol SMAssetInfo
@end

@interface SMAssetInfo : SMBaseObject

/* Title of asset 
 */
@property(nonatomic) NSString* title;
/* Sub title of asset [optional]
 */
@property(nonatomic) NSString* subtitle;
/* Asset description [optional]
 */
@property(nonatomic) NSString* _description;
/* Is the asset active 
 */
@property(nonatomic) NSNumber* isActive;
/* Is the asset generic 
 */
@property(nonatomic) NSNumber* isGeneric;
/* List of asset tags as string 
 */
@property(nonatomic) NSString* tags;
/* Date and time of creation 
 */
@property(nonatomic) NSDate* created;
/* Date and time of modification 
 */
@property(nonatomic) NSDate* modified;
/* Unique identifier. 
 */
@property(nonatomic) NSNumber* _id;
/* Unique identifier, uuid4 
 */
@property(nonatomic) NSString* uid;
/* Campdign ID. [optional]
 */
@property(nonatomic) NSNumber* campaignId;
/* Unique identifier of campaign, uuid4 [optional]
 */
@property(nonatomic) NSString* campaignUid;
/* Advertiser ID. 
 */
@property(nonatomic) NSNumber* advertiserId;
/* Unique identifier of advertiser, uuid4 
 */
@property(nonatomic) NSString* advertiserUid;
/* TBSO2 source file [optional]
 */
@property(nonatomic) NSString* fileTbso;
/* TBSO2 Standalone file [optional]
 */
@property(nonatomic) NSString* fileStandalone;
/* TBSO2 iOS file [optional]
 */
@property(nonatomic) NSString* fileIos;
/* TBSO2 Android file [optional]
 */
@property(nonatomic) NSString* fileAndroid;
/* Preview image [optional]
 */
@property(nonatomic) NSString* filePreview;
/* Smarttab icon file [optional]
 */
@property(nonatomic) NSString* fileIcon;
/* Smarttab image file [optional]
 */
@property(nonatomic) NSString* fileImage;
/* Coupon file [optional]
 */
@property(nonatomic) NSString* fileCoupon;
/* Mobile video [optional]
 */
@property(nonatomic) NSString* videoMobile;
/* Standalone video [optional]
 */
@property(nonatomic) NSString* videoStandalone;
/* URL to merchant store 
 */
@property(nonatomic) NSString* whereToBuy;
/* Category ID 
 */
@property(nonatomic) NSNumber* category;
/* Category title [optional]
 */
@property(nonatomic) NSString* categoryTitle;

@end
