#import <Foundation/Foundation.h>
#import "SMBaseObject.h"

/**
* Trivver API Development
* API for Trivver project
*
* OpenAPI spec version: 0.0.107
* Contact: trivver@saritasa.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/



@protocol SMUserSession
@end

@interface SMUserSession : SMBaseObject

/* First name of player [optional]
 */
@property(nonatomic) NSString* firstName;
/* Last name of player [optional]
 */
@property(nonatomic) NSString* lastName;
/* Age of player [optional]
 */
@property(nonatomic) NSNumber* age;
/* Sex of player [optional]
 */
@property(nonatomic) NSString* sex;
/* Player state [optional]
 */
@property(nonatomic) NSString* state;
/* Player city [optional]
 */
@property(nonatomic) NSString* city;
/* Player country [optional]
 */
@property(nonatomic) NSString* country;
/* Player IP address [optional]
 */
@property(nonatomic) NSString* ipAddr;
/* Device ID [optional]
 */
@property(nonatomic) NSString* deviceId;

@end
